# Generated by Django 6.0.3 on 2026-04-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='imported_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='processed_text',
        ),
    ]
