# Generated by Django 6.0.3 on 2026-04-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_imported_text_documents_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='processed',
            field=models.BooleanField(default='False'),
        ),
    ]
