# Generated by Django 6.0.3 on 2026-04-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_documents_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='import/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documents',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
