# Generated by Django 6.0.4 on 2026-04-15 11:47

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('api', '0004_alter_documents_file_alter_documents_processed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='CVAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text_chunk', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.documents')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generatedJson', models.JSONField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
